### ISSUE TITLE
Function Talents: Incorrect TTL 

### ISSUE THREAD

**Issue by nayakned** [GENIVI/iot-event-analytics#47]
The Function Talents in Python SDK are not working since the last set of pull requests.
The TTL of the talent being registered is apparently 0 and the ConfigManager gives out an error.
```
INFO [ConfigManager] : Discovery info of math is invalid. Errors: .config.outputs['math.multiply-in'].ttl should be >= 1000
```
This issue can be reproduced on the develop commit 6dd73b9

How to reproduce:
1. Start the platform
```
docker-compose -f docker-compose.mosquitto.yml -f docker-compose.platform.yml up --remove-orphans
```

2. Start the talent
```
src/sdk/python/examples/functions $ python run.py
```
This throws an error in the talent.
```
ERROR [ Talent.math-d35947e6 ]: An error occured. Code 4002 aa2e5c78-3655-4089-bc41-8ea809e674c1
```

**Comment by llakie** [comment]
Which version of the SDK and the platform are you using? This is due to a setting in the JSON schema, which is used to validate incoming discovery responses. This was fixed quite a long time ago. Check the ttl property <iot-event-analytics root folder>/resources/feature.schema.json it should read:
`json
"ttl": { "oneOf": [ { "type": "number", "const": 0 }, { "type": "number", "minimum": 1000 } ] }`

This means: All values must be over 1000, with the exception of 0, which indicates a volatile feature.
Can you pleas check that?
If you cannot find the property like mentioned above, please upgrade to the latest version of develop.

**Comment by nayakned** [comment]
I had tried earlier with the git commit 6dd73b9. 
Now tried again with f9ec110. Also re-executed yarn after pulling the new set of commits.
The SDK version seems to be 0.4.0.
The problem persists however.

Interestingly, function talents in javascript work fine. The problem exists only in python SDK for me.

P.S.: How do I find the platform version? Unfortunately, the version is not mentioned in the log output.
Perhaps, it is a good idea to output the version number of the platform and SDK in the corresponding console outputs.

**Comment by nayakned** [comment]
The resources/feature.schema.json shows the ttl property as follows:

```
"ttl": {
                    "oneOf": [
                        {
                            "type": "number",
                            "const": 0
                        },
                        {
                            "type": "number",
                            "minimum": 1000
                        }
                    ]
                },

```

**Comment by nayakned** [comment]
Is the TTL set to 0 in the Python SDK. Here in code.
https://github.com/GENIVI/iot-event-analytics/blob/develop/src/sdk/python/pkg/iotea/core/talent_func.py#L32
https://github.com/GENIVI/iot-event-analytics/blob/develop/src/sdk/python/pkg/iotea/core/talent_func.py#L43

I changed it to 1000 and then it works.

**Comment by llakie** [comment]
Your feature.schema.json seems to be correct. We have to treat function inputs and outputs as volatile features, which are not stored within an instance. Otherwise rulesets may evaluate wrong, if these values remain present.
Please leave it at 0 as it's written in the SDK. I will check out using the Python examples, why it does not work for you.

**Comment by llakie** [comment]
> P.S.: How do I find the platform version? Unfortunately, the version is not mentioned in the log output.
> Perhaps, it is a good idea to output the version number of the platform and SDK in the corresponding console outputs.

The platform version can be retrieved from the _package.json_ file

**Comment by wenwenchenbosch** [comment]
@nayakned I just tested the function example with current develop branch 41ac311eb5bafed64d90adb8f880a919fc0826e4. I can not see the error. only some warning there:
```
2021-04-15T19:22:51.239Z WARNING [ hbmqtt.mqtt.protocol.handler ]: Unhandled exception: 'Lock' object is not iterable
2021-04-15T19:22:51.239Z WARNING [ hbmqtt.client ]: Connection failed: TypeError("'Lock' object is not iterable")
```

something goes wrong, right?

**Comment by wenwenchenbosch** [comment]
found out with @nayakned that my issues is because of using `python3.9`. hbmqtt is still not compatible with `python3.9`. see https://github.com/beerfactory/hbmqtt/issues/223 

using `python3.8.9`, the python example works well

**Comment by nayakned** [comment]
This problem looks to have been resolved in commit 45dfb0e.
Also confirmed by @wenwenchenbosch.
